---
apiVersion: batch/v1
kind: Job
metadata:
  name: secret-smuggler
spec:
  template:
    spec:
      serviceAccountName: "opi"
      restartPolicy: OnFailure
      containers:
      - name: smuggle
        image: eirini/secret-smuggler:{{ .Values.opi.image_tag }}
        env:
        - name: SECRET_NAME
          value: secrets-{{ .Values.scf.version }}-{{ .Values.scf.secrets_generation_counter }}
        - name: UAA_NAMESPACE
          value: uaa
        - name: SCF_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: OPI_NAMESPACE
          value: {{ .Values.opi.namespace }}
