---
apiVersion: v1
kind: Service
metadata:
  name: "eirini-opi"
spec:
{{- if not .Values.opi.use_registry_ingress }}
  externalIPs: {{ .Values.kube.external_ips | toJson }}
{{- end }}
  ports:
    - port: 8085
      protocol: TCP
      name: opi
  selector:
    name: "eirini"
