---
apiVersion: "v1"
data:
  .dockercfg: {{ printf "{%q:{%q:%q,%q:%q,%q:%q}}" .Values.kube.registry.hostname "username" (default "" .Values.kube.registry.username) "password" (default "" .Values.kube.registry.password) "auth" (printf "%s:%s" .Values.kube.registry.username .Values.kube.registry.password | b64enc) | b64enc }}
kind: "Secret"
metadata:
  name: "registry-credentials"
  labels:
    skiff-role-name: "registry-credentials"
    app.kubernetes.io/component: "registry-credentials"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
type: "kubernetes.io/dockercfg"
